// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TradingSimulator.Infrastructure.Persistence;

#nullable disable

namespace TradingSimulator.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDatabaseContext))]
    partial class ApplicationDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("trading")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TradingSimulator.Infrastructure.Persistence.Entities.CandlestickRecord", b =>
                {
                    b.Property<string>("Symbol")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("symbol");

                    b.Property<short>("Interval")
                        .HasColumnType("smallint")
                        .HasColumnName("interval");

                    b.Property<DateTimeOffset>("BucketStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bucket_start");

                    b.Property<decimal>("ClosePrice")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("close_price");

                    b.Property<decimal>("HighPrice")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("high_price");

                    b.Property<decimal>("LowPrice")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("low_price");

                    b.Property<decimal>("OpenPrice")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("open_price");

                    b.Property<int>("TradeCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("trade_count");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Volume")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("volume");

                    b.HasKey("Symbol", "Interval", "BucketStart");

                    b.ToTable("candlesticks", "trading", t =>
                        {
                            t.HasCheckConstraint("ck_candlesticks_high_low", "high_price >= low_price");

                            t.HasCheckConstraint("ck_candlesticks_prices_positive", "open_price > 0 AND high_price > 0 AND low_price > 0 AND close_price > 0");

                            t.HasCheckConstraint("ck_candlesticks_volume_non_negative", "volume >= 0");
                        });
                });

            modelBuilder.Entity("TradingSimulator.Infrastructure.Persistence.Entities.HoldingRecord", b =>
                {
                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_id");

                    b.Property<string>("Symbol")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("symbol");

                    b.Property<decimal>("AveragePrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("average_price");

                    b.Property<long>("ReservedQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("reserved_quantity");

                    b.Property<long>("TotalQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("total_quantity");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("PortfolioId", "Symbol");

                    b.HasIndex("Symbol");

                    b.ToTable("holdings", "trading", t =>
                        {
                            t.HasCheckConstraint("ck_holdings_avg_price_non_negative", "average_price >= 0");

                            t.HasCheckConstraint("ck_holdings_reserved_le_total", "reserved_quantity <= total_quantity");

                            t.HasCheckConstraint("ck_holdings_reserved_non_negative", "reserved_quantity >= 0");

                            t.HasCheckConstraint("ck_holdings_total_non_negative", "total_quantity >= 0");
                        });
                });

            modelBuilder.Entity("TradingSimulator.Infrastructure.Persistence.Entities.OrderRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("FilledQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("filled_quantity");

                    b.Property<bool>("IsSimulated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_simulated");

                    b.Property<long>("OriginalQuantity")
                        .HasColumnType("bigint")
                        .HasColumnName("original_quantity");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("price");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("rejection_reason");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.Property<short>("Side")
                        .HasColumnType("smallint")
                        .HasColumnName("side");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("status");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("symbol");

                    b.Property<DateTimeOffset?>("TerminatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("terminated_at");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TerminatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_orders_terminated")
                        .HasFilter("terminated_at IS NOT NULL");

                    b.HasIndex("UserId", "Status", "CreatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_orders_user_status");

                    b.HasIndex("Symbol", "Side", "Price", "CreatedAt")
                        .HasDatabaseName("ix_orders_active_book")
                        .HasFilter("status IN (0, 1)");

                    b.ToTable("orders", "trading", t =>
                        {
                            t.HasCheckConstraint("ck_orders_filled_le_original", "filled_quantity <= original_quantity");

                            t.HasCheckConstraint("ck_orders_filled_non_negative", "filled_quantity >= 0");

                            t.HasCheckConstraint("ck_orders_limit_has_price", "(type = 0 AND price IS NOT NULL AND price > 0) OR (type = 1 AND price IS NULL)");

                            t.HasCheckConstraint("ck_orders_quantity_positive", "original_quantity > 0");

                            t.HasCheckConstraint("ck_orders_side_range", "side IN (0, 1)");

                            t.HasCheckConstraint("ck_orders_status_range", "status IN (0, 1, 2, 3, 4)");

                            t.HasCheckConstraint("ck_orders_terminal_has_terminated_at", "(status IN (2, 3, 4)) = (terminated_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_orders_type_range", "type IN (0, 1)");
                        });
                });

            modelBuilder.Entity("TradingSimulator.Infrastructure.Persistence.Entities.PortfolioRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_portfolios_user");

                    b.ToTable("portfolios", "trading");
                });

            modelBuilder.Entity("TradingSimulator.Infrastructure.Persistence.Entities.PortfolioResetRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Reason")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("ResetAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reset_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ResetAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_portfolio_resets_user_time");

                    b.ToTable("portfolio_resets", "trading");
                });

            modelBuilder.Entity("TradingSimulator.Infrastructure.Persistence.Entities.SymbolRecord", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<decimal>("TickSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,4)")
                        .HasDefaultValue(0.01m)
                        .HasColumnName("tick_size");

                    b.HasKey("Code");

                    b.ToTable("symbols", "trading", t =>
                        {
                            t.HasCheckConstraint("ck_symbols_tick_size_positive", "tick_size > 0");
                        });

                    b.HasData(
                        new
                        {
                            Code = "AAPL",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Name = "Apple Inc.",
                            TickSize = 0.01m
                        });
                });

            modelBuilder.Entity("TradingSimulator.Infrastructure.Persistence.Entities.TradeRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("BuyOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("buy_order_id");

                    b.Property<Guid>("BuyerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_user_id");

                    b.Property<DateTimeOffset>("ExecutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at");

                    b.Property<Guid>("ExternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("external_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("price");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint")
                        .HasColumnName("quantity");

                    b.Property<Guid>("SellOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sell_order_id");

                    b.Property<Guid>("SellerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_user_id");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("symbol");

                    b.HasKey("Id");

                    b.HasIndex("BuyOrderId")
                        .HasDatabaseName("ix_trades_buy_order");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ux_trades_external_id");

                    b.HasIndex("SellOrderId")
                        .HasDatabaseName("ix_trades_sell_order");

                    b.HasIndex("BuyerUserId", "ExecutedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_trades_buyer_time");

                    b.HasIndex("SellerUserId", "ExecutedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_trades_seller_time");

                    b.HasIndex("Symbol", "ExecutedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_trades_symbol_time");

                    b.ToTable("trades", "trading", t =>
                        {
                            t.HasCheckConstraint("ck_trades_orders_distinct", "buy_order_id <> sell_order_id");

                            t.HasCheckConstraint("ck_trades_price_positive", "price > 0");

                            t.HasCheckConstraint("ck_trades_quantity_positive", "quantity > 0");

                            t.HasCheckConstraint("ck_trades_users_distinct", "buyer_user_id <> seller_user_id");
                        });
                });

            modelBuilder.Entity("TradingSimulator.Infrastructure.Persistence.Entities.UserRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_users_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ux_users_username");

                    b.ToTable("users", "trading");
                });

            modelBuilder.Entity("TradingSimulator.Infrastructure.Persistence.Entities.UserSessionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_user_sessions_expires");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_sessions_user");

                    b.ToTable("user_sessions", "trading");
                });

            modelBuilder.Entity("TradingSimulator.Infrastructure.Persistence.Entities.WalletRecord", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasDefaultValue("USD")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<decimal>("ReservedBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("reserved_balance");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.Property<decimal>("TotalBalance")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("total_balance");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.ToTable("wallets", "trading", t =>
                        {
                            t.HasCheckConstraint("ck_wallets_reserved_le_total", "reserved_balance <= total_balance");

                            t.HasCheckConstraint("ck_wallets_reserved_non_negative", "reserved_balance >= 0");

                            t.HasCheckConstraint("ck_wallets_total_non_negative", "total_balance >= 0");
                        });
                });

            modelBuilder.Entity("TradingSimulator.Infrastructure.Persistence.Entities.CandlestickRecord", b =>
                {
                    b.HasOne("TradingSimulator.Infrastructure.Persistence.Entities.SymbolRecord", "SymbolNavigation")
                        .WithMany()
                        .HasForeignKey("Symbol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SymbolNavigation");
                });

            modelBuilder.Entity("TradingSimulator.Infrastructure.Persistence.Entities.HoldingRecord", b =>
                {
                    b.HasOne("TradingSimulator.Infrastructure.Persistence.Entities.PortfolioRecord", "Portfolio")
                        .WithMany("Holdings")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradingSimulator.Infrastructure.Persistence.Entities.SymbolRecord", "SymbolNavigation")
                        .WithMany()
                        .HasForeignKey("Symbol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Portfolio");

                    b.Navigation("SymbolNavigation");
                });

            modelBuilder.Entity("TradingSimulator.Infrastructure.Persistence.Entities.OrderRecord", b =>
                {
                    b.HasOne("TradingSimulator.Infrastructure.Persistence.Entities.SymbolRecord", "SymbolNavigation")
                        .WithMany()
                        .HasForeignKey("Symbol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TradingSimulator.Infrastructure.Persistence.Entities.UserRecord", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SymbolNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TradingSimulator.Infrastructure.Persistence.Entities.PortfolioRecord", b =>
                {
                    b.HasOne("TradingSimulator.Infrastructure.Persistence.Entities.UserRecord", "User")
                        .WithOne("Portfolio")
                        .HasForeignKey("TradingSimulator.Infrastructure.Persistence.Entities.PortfolioRecord", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TradingSimulator.Infrastructure.Persistence.Entities.PortfolioResetRecord", b =>
                {
                    b.HasOne("TradingSimulator.Infrastructure.Persistence.Entities.UserRecord", "User")
                        .WithMany("PortfolioResets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TradingSimulator.Infrastructure.Persistence.Entities.TradeRecord", b =>
                {
                    b.HasOne("TradingSimulator.Infrastructure.Persistence.Entities.OrderRecord", "BuyOrder")
                        .WithMany()
                        .HasForeignKey("BuyOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TradingSimulator.Infrastructure.Persistence.Entities.OrderRecord", "SellOrder")
                        .WithMany()
                        .HasForeignKey("SellOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TradingSimulator.Infrastructure.Persistence.Entities.SymbolRecord", "SymbolNavigation")
                        .WithMany()
                        .HasForeignKey("Symbol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BuyOrder");

                    b.Navigation("SellOrder");

                    b.Navigation("SymbolNavigation");
                });

            modelBuilder.Entity("TradingSimulator.Infrastructure.Persistence.Entities.UserSessionRecord", b =>
                {
                    b.HasOne("TradingSimulator.Infrastructure.Persistence.Entities.UserRecord", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TradingSimulator.Infrastructure.Persistence.Entities.WalletRecord", b =>
                {
                    b.HasOne("TradingSimulator.Infrastructure.Persistence.Entities.UserRecord", "User")
                        .WithOne("Wallet")
                        .HasForeignKey("TradingSimulator.Infrastructure.Persistence.Entities.WalletRecord", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TradingSimulator.Infrastructure.Persistence.Entities.PortfolioRecord", b =>
                {
                    b.Navigation("Holdings");
                });

            modelBuilder.Entity("TradingSimulator.Infrastructure.Persistence.Entities.UserRecord", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Portfolio");

                    b.Navigation("PortfolioResets");

                    b.Navigation("Sessions");

                    b.Navigation("Wallet");
                });
#pragma warning restore 612, 618
        }
    }
}
